### ISSUE TITLE
Kodi 17.4 no install

### ISSUE THREAD

**Issue by Hagit60** [arnesongit/repository.tidal2#1]
Hi Arnesongit, on kodi 17.4 I could install Tidal 2.0.0-beta21 in the past, but now I cannot install the new repsitory.tidal2, (aka 2.0.1). How to solve? Please help.

**Comment by arnesongit** [comment]
Did you try the repository from the "until-leia" branch ? The files from the "master" branch can only be used for Kodi >= 19

**Comment by Hagit60** [comment]
> Did you try the repository from the "until-leia" branch ? The files from the "master" branch can only be used for Kodi >= 19

Yes I have tried the "until-leia' branch. Removed Tidal 2.0.0-beta21. Tried again but did not work again. Then I installed Tidal 2.0.0-beta21 that worked again....

**Comment by arnesongit** [comment]
Before you install the new [repository.tidal2-0.1.0.zip](https://github.com/arnesongit/repository.tidal2/blob/until-leia/repository.tidal2/repository.tidal2-0.1.0.zip?raw=true) you have to uninstall the old TIDAL2 repository addon.
Did you do that ? Which platform do you use (Windows, macOS, Linux, etc.) ?

**Comment by Hagit60** [comment]
> Before you install the new [repository.tidal2-0.1.0.zip](https://github.com/arnesongit/repository.tidal2/blob/until-leia/repository.tidal2/repository.tidal2-0.1.0.zip?raw=true) you have to uninstall the old TIDAL2 repository addon.
> Did you do that ? Which platform do you use (Windows, macOS, Linux, etc.) ?
Thanx for your reply. Yes, as written I did this.  Platform is Linux. On an other device I installed LibreElec with Kodi18.9 fresh. Then the addon  repository.tidal2-0.1.0.zip failed to install.  Log shows:  repository.tidal2-0.1.0.zip failed due to an invalid structure.

**Comment by arnesongit** [comment]
Hello Hagit60,
I tried the repository addon with Windows 10 and Kodi 17.6 and also on macOS 10.15.7 with Kodi 17.4 without any problems. And I also use LibreELEC 9.2.6 with Kodi 18.9 on an Asrock BeeBox-S in my livingroom and had no problems with the TIDAL2 repository addon for Kodi Leia.

**Comment by Hagit60** [comment]
Hello Arnesongit, manny thanks for your writting and testing! It seems the addons downloaded from my Nas to Kodi give the trouble writting to older hardware, (ATV 1e gen and older x86 machine) Writting from an USB stick solves the problem. On OSMC Kodi 17.4 (ATV1) and LibreELEC Kodi18.9 (x86) and Mibox S4 Kodi 19 your script works awsome!  Logging in was the next challenge, but after some research I finally managed to listen to music. :-) Manny thanks for writing, testing and sharing!!
